### ISSUE TITLE
Project Idea

### ISSUE THREAD

**Issue by Paul2708** [brettsaunders21/SpigotRelease#7]
Hey, I just wanted to ask what the project is all about.

Greetings, Paul

**Comment by brettsaunders21** [comment]
Automatically release spigot plugins

**Comment by Paul2708** [comment]
Okay I see, I tried the same, however, I was not successful. Did you come up with a working prototype?

**Comment by brettsaunders21** [comment]
Yes, I just used puppeteer to control a headless browser
